### ISSUE TITLE
Character can walk off screen

### ISSUE THREAD

**Issue by array-in-a-matrix** [sarasauruss/take-a-walk#1]
Character can walk off screen.

![Screenshot 2023-04-16 at 18-51-34 Sketch](https://user-images.githubusercontent.com/78233840/232348062-0fad8801-cb1a-4000-a312-a64b53f7f015.png)

**Comment by AsherAnd** [comment]
Having the same issue

**Comment by array-in-a-matrix** [comment]
lead developer said this is intentional on matrix, closing.
